### PR TITLE
Enable installation to NVMe M.2 SSDs

### PR DESCRIPTION
**Pull request by KodeCR**
This is a collection of patches to make NVMe disk(s) the installable disks so that DSM can boot and run from NVMe and allow the SATA disks to hibernate:
- Add NVMe disks to installable disks
- Remove SATA disks from DSM root /dev/md0
- Fix NVMe accesses and SMART checks waking up hibernated disks
- Suppress warning that SATA system partitions aren't part of the root RAID array
- Add service to sync SATA system partitions at shutdown

It only supports 7.2.1, (but it wouldn't be hard to add the patches for older versions)

### CODE REVIEW

**Comment by AuxXxilium** [comment]
thanks for this addon, i added it at made the files executable, will try it later

**Comment by AuxXxilium** [comment]
@KodeCR were you able to use the nvme disk as storage pool? i tried multiple models and was not able to set it as storage pool.

**Comment by KodeCR** [comment]
@AuxXxilium, yes, I installed DSM to NVMe and then I could create a storage pool in storage manager once installed. I found out today that you need a SATA drive as well to create the NVMe storage pool (I use this to install to NVMe so my SATA disks can sleep), so apparently there is another check to patch somewhere for storage manager to enable NVMe only.

**Comment by AuxXxilium** [comment]
> NVMe

this is possible, i will look into it at weekend. only install to nvme will not work if you add sata disks. because dsm partition will be synced across all disks.

**Comment by KodeCR** [comment]
> only install to nvme will not work if you add sata disks. because dsm partition will be synced across all disks

That is what the patches address. The first patches scemd to include nvme disks in the list of installable disks, the synodiskport wrapper then filter out the SATA disks when constructing md0 so that the DSM partition is NVMe only, at shutdown the DSM partition is synced with the SATA disks again so that you could still boot from them.

**Pull request merged**
